spring:
  datasource:
    username: ${POSTGRESQL_USERNAME:shira}
    password: ${POSTGRESQL_PASSWORD:shira}
    url: jdbc:postgresql://${POSTGRESQL_HOST:127.0.0.1}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:runtimeassignment}?serverTimezone=UTC
  application:
    name: ${APPLICATION_NAME:runtimeassignment
  main:
    banner-mode: ${SPRING_BANNER_MODE:OFF}
  lifecycle:
    timeout-per-shutdown-phase: 3m

server:
  port: ${HTTP_PORT:8082}
  tomcat:
    mbeanregistry:
      enabled: ${TOMCAT_MBEAN_REGISTRY:false}
    threads:
      min-spare: ${TOMCAT_THREADS_MIN_SPARE:200}
  error:
    include-message: always
    include-binding-errors: always